library(tidyverse)
library(here)
dat <- readr::read_rds(here("data","derived","sinasc_recoded.rds"))
if (nrow(dat)!=12378) stop("Expected 12,378 cohort rows; found ",nrow(dat))
outcome_valid <- dat |> filter(!is.na(outcome))
race_valid <- outcome_valid |> filter(!is.na(race))
analysis_cc <- race_valid |> filter(!is.na(region),!is.na(age_group),!is.na(year),!is.na(education))
audit_funnel <- tibble(stage=c("Q00-Q07 cohort","Classifiable Kotelchuck","Classifiable Kotelchuck + valid race/color","Common complete-case sample"), n=c(nrow(dat),nrow(outcome_valid),nrow(race_valid),nrow(analysis_cc)))
print(audit_funnel)
stopifnot(nrow(outcome_valid)==11745)
stopifnot(nrow(analysis_cc)==11277)
stopifnot(sum(analysis_cc$outcome==1)==3864)
stopifnot(sum(analysis_cc$outcome==0)==7413)
readr::write_csv(audit_funnel, here("outputs","tables","audit_funnel.csv"))
readr::write_rds(analysis_cc, here("data","derived","analysis_cc.rds"))
message("All frozen sample checks passed.")
