library(tidyverse)
library(here)
library(binom)
dat <- readr::read_rds(here("data","derived","analysis_cc.rds"))
write_simple <- function(var,name){dat |> count({{var}}) |> mutate(percent=n/sum(n)) |> write_csv(here("outputs","tables",name))}
write_simple(race,"table1_race.csv")
write_simple(age_group,"table1_age.csv")
write_simple(education,"table1_education.csv")
write_simple(region,"table1_region.csv")
write_simple(year,"table1_year.csv")
write_simple(pregnancy_type,"table1_pregnancy_type.csv")
write_simple(kotelchuck_cat,"table1_kotelchuck.csv")
write_simple(outcome_label,"table1_outcome.csv")
table2 <- dat |> group_by(race) |> summarise(n=n(),events=sum(outcome==1),prevalence=events/n,.groups="drop") |> rowwise() |> mutate(ci=list(binom::binom.wilson(events,n)),lower=ci$lower,upper=ci$upper) |> ungroup() |> select(-ci)
annual <- dat |> group_by(year,race) |> summarise(n=n(),events=sum(outcome==1),prevalence=events/n,.groups="drop") |> rowwise() |> mutate(ci=list(binom::binom.wilson(events,n)),lower=ci$lower,upper=ci$upper) |> ungroup() |> select(-ci)
write_csv(table2,here("outputs","tables","table2_prevalence_race.csv"))
write_csv(annual,here("outputs","tables","annual_prevalence_race.csv"))
print(table2)
