library(tidyverse)
library(here)
library(sandwich)
library(lmtest)
dat <- readr::read_rds(here("data","derived","analysis_cc.rds"))
m0 <- glm(outcome ~ race, family=poisson(link="log"), data=dat)
m1 <- glm(outcome ~ race + region + age_group + year, family=poisson(link="log"), data=dat)
m2 <- glm(outcome ~ race + region + age_group + year + education, family=poisson(link="log"), data=dat)
robust_tidy <- function(model,model_name){V<-sandwich::vcovHC(model,type="HC0");ct<-lmtest::coeftest(model,vcov.=V);tibble(term=rownames(ct),estimate_log=ct[,1],robust_se=ct[,2],statistic=ct[,3],p_value=ct[,4],pr=exp(estimate_log),conf_low=exp(estimate_log-1.96*robust_se),conf_high=exp(estimate_log+1.96*robust_se),model=model_name)}
all_models <- bind_rows(robust_tidy(m0,"M0"),robust_tidy(m1,"M1"),robust_tidy(m2,"M2"))
race_models <- all_models |> filter(stringr::str_detect(term,"^race")) |> mutate(race=stringr::str_remove(term,"^race")) |> select(model,race,pr,conf_low,conf_high,p_value)
print(race_models)
write_csv(all_models,here("outputs","tables","all_model_coefficients.csv"))
write_csv(race_models,here("outputs","tables","table3_race_prs.csv"))
saveRDS(list(M0=m0,M1=m1,M2=m2),here("data","derived","models.rds"))
