library(tidyverse)
library(here)
library(sandwich)
library(lmtest)
dat <- readr::read_rds(here("data","derived","analysis_cc.rds"))
annual <- readr::read_csv(here("outputs","tables","annual_prevalence_race.csv"),show_col_types=FALSE)
m_no_inter <- glm(outcome ~ race + year + region + age_group + education, family=poisson(link="log"), data=dat)
m_inter <- glm(outcome ~ race*year + region + age_group + education, family=poisson(link="log"), data=dat)
interaction_test <- lmtest::waldtest(m_no_inter,m_inter,vcov=function(x)sandwich::vcovHC(x,type="HC0"),test="Chisq")
capture.output(interaction_test,file=here("outputs","logs","race_year_interaction_wald.txt"))
major <- annual |> filter(race %in% c("White","Black","Brown"))
p1 <- ggplot(major,aes(x=as.integer(year),y=prevalence,group=race,linetype=race))+geom_line(linewidth=.7)+geom_point(size=2)+scale_x_continuous(breaks=2019:2023)+scale_y_continuous(labels=scales::percent_format(accuracy=1))+labs(x="Year",y="Below-adequate prenatal care utilization",linetype="Maternal race/color")+theme_minimal(base_size=11)
ggsave(here("outputs","figures","figure1_major_race_groups.png"),p1,width=7.2,height=4.6,dpi=300)
small <- annual |> filter(race %in% c("Yellow","Indigenous"))
pS1 <- ggplot(small,aes(x=as.integer(year),y=prevalence,group=race,linetype=race))+geom_errorbar(aes(ymin=lower,ymax=upper),width=.08)+geom_line(linewidth=.7)+geom_point(size=2)+scale_x_continuous(breaks=2019:2023)+scale_y_continuous(labels=scales::percent_format(accuracy=1),limits=c(0,1))+labs(x="Year",y="Below-adequate prenatal care utilization",linetype="Maternal race/color")+theme_minimal(base_size=11)
ggsave(here("outputs","figures","figureS1_small_race_groups.png"),pS1,width=7.2,height=4.6,dpi=300)
